version: '2'
services:
  netsuivi1-app:
    image: netsuivi1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://netsuivi1-postgresql:5432/NETSUIVI1
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  netsuivi1-postgresql:
    extends:
      file: postgresql.yml
      service: netsuivi1-postgresql
