version: '2'
services:
  netsuivi1-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/NETSUIVI1/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=NETSUIVI1
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
